// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Vords",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "Vords",
            targets: ["AppModule"],
            bundleIdentifier: "com.claudiomarciello.Vords",
            teamIdentifier: "Z993Z64L49",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.indigo),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .microphone(purposeString: "We need to access your microphone to collect the words you pronounce and use them for scoring your points!"),
                .speechRecognition(purposeString: "We need to use Speech Recognition to understand which words you pronounce!")
            ],
            appCategory: .games
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ]
)